{{- if .Values.createGrafanaSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: Y29saW5zYWRtaW4= #YWRtaW4=   # admin
  passphrase: Rml0eW91cjIwMTk= #YWRtaW4= # admin
{{- end }}
